const σ_R0_non_centered_mean = -3
const σ_R0_non_centered_sd = 0.2
const σ_IFR_non_centered_mean = -2.5
const σ_IFR_non_centered_sd = 0.13
const σ_α_non_centered_mean = -3
const σ_α_non_centered_sd = 0.2
const R₀_init_non_centered_mean = 0.0
const R₀_init_non_centered_sd = 0.5
const IFR_init_non_centered_mean = -5.3
const IFR_init_non_centered_sd = 0.4
const α_init_non_centered_mean = 1.35
const α_init_non_centered_sd = 0.15
const S_SEI_non_centered_mean = 6
const S_SEI_non_centered_sd = 0.5
const I_EI_non_centered_mean = 0.6
const I_EI_non_centered_sd = 0.03
const dur_latent_non_centered_mean = log(3 / 7)
const dur_latent_non_centered_sd = 0.25
const dur_infectious_non_centered_mean = log(5 / 7)
const dur_infectious_non_centered_sd = 0.2
const ρ_death_non_centered_mean = 2.3
const ρ_death_non_centered_sd = 0.2
const ϕ_cases_non_centered_mean = 7.0
const ϕ_cases_non_centered_sd = 0.24
const ϕ_deaths_non_centered_mean = 5.4
const ϕ_deaths_non_centered_sd = 0.46 